services:
  postgres:
    image: postgres:17
    container_name: event-booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_booking_api
    ports:
      - "7001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: